### PR TITLE
Shsh9933 hw1b

### PR DESCRIPTION
**Pull request by shikhashahri**

### CODE REVIEW

**Review by j-griffith — CHANGES_REQUESTED** [review]
It looks like you're placing these files in the root directory of the repo.  You need to create a directory with your student ID and a hw1b directory and move the files there.  For example, you should have:

TLEN-5830
- - shikashahri
        -- hw1b
             -- README.md
             -- *.tf
             -- *.tpl

**Review by j-griffith — DISMISSED** [review]

**Comment by j-griffith** [comment]
You'll need to fix your README files merge conflicts, if you're stuck figuring out how to do this let me know and I can walk through it with you.

**Comment by shikhashahri** [comment]
I am not able to understand the conflict here. I have done multiple commits
and they seem to be all mixed up now. I tried running the command "git
rebase -i". I'm just not sure how many commits to squash here.

Shikha Shahri
Graduate Student
Interdisciplinary Telecom Program - Network Engineering
University of Colorado Boulder
Phone: +1 720-938-7903
Email: shikha.shahri@colorado.edu

**Comment by shikhashahri** [comment]
removed the files from the root directory. no more conflicts seen.

**Pull request merged**
